---
title: New York Labor for Bernie
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
parent: Labor for Bernie
parent_url: https://laborforbernie2020.org/
contact_email: contact@nylaborforbernie.org
description: New York Labor for Bernie is an independent campaign to elect Bernie
  Sanders in 2020 by building a mass movement of union members and labor activists.
